# .github/workflows/

name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  TestRun:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        npm install

    # Step 4: Run Playwright tests
    - name: Run Playwright tests
      run: |
        npx playwright install  # Install browsers
        npx playwright test --reporter=line > result || echo "Run Failed" # Run Playwright tests


    - name: Upload HTML report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/**

    # Step 5: Create an issue if the test fails
    - name: Create GitHub issue on failure
      if: failure()  # This ensures the issue is created only on failure
      run: |
        username=$(git config --get user.name)
        curl -X POST \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"title":"CI Build Failed","body":"The CI build failed on the latest commit. Please investigate.\n\nTest Results:\n\n'"$test_results"'","assignees":["'"$username"'"],"labels":["bug"]}' \
          "https://api.github.com/repos/${{ github.repository }}/issues"