# .github/workflows/

name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  TestRun:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        npm install

    # Step 4: Run Playwright tests
    - name: Run Playwright tests
      id: playwright_tests
      continue-on-error: true
      run: |
        set -o pipefail
        npx playwright install  # Install browsers
        npx playwright test | tee results     # Run Playwright tests
        exit_code=$?
        echo "Exit Code $exit_code"

        echo "TEST_RESULTS<<EOF" >> $GITHUB_ENV
        cat results >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        if grep -iqE "error|timeout|failed" results; then
          echo "TEST_FAILED=true" >> $GITHUB_ENV  # Flag failure for later
          exit_code=1
        else
          echo "TEST_FAILED=false" >> $GITHUB_ENV
        fi

        exit $exit_code

    - name: Debug Test Faliure Variable
      run: |
        echo "TEST_FAILED=${{ env.TEST_FAILED }}"


    # Step 5: Create an issue if the test fails
    - name: Create GitHub issue on failure
      if: env.TEST_FAILED   # This ensures the issue is created only on failure
      run: |
          test_results="${{ env.TEST_RESULTS }}"
          test_results="${test_results:0:5000}"  # Trim output

          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "title": "CI Build Failed",
              "body": "The CI build failed. Please investigate.\n\n**Test Results:**\n```\n'"$test_results"'\n```\n\n[View full Playwright report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})",
              "labels": ["bug"]
            }' \
            "https://api.github.com/repos/${{ github.repository }}/issues"
          echo "Tests passed, skipping issue creation."

    - name: Upload HTML report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/**
